# Generated by Django 5.1.7 on 2025-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('roof_size', models.IntegerField(default=0)),
                ('roof_type', models.CharField(max_length=200)),
                ('project_city', models.CharField(max_length=200)),
                ('project_state', models.CharField(max_length=200)),
                ('project_date', models.DateTimeField(verbose_name='project-date')),
            ],
        ),
    ]
